### ISSUE TITLE
September maintenance checklist

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#245]
**Maintainer on call**: @i0natan

**Updates**

- [] Update top badges with best practices item count, last update date and Node.js version
- [] Ensure all translations are aligned with the English version
- [] Update 'thank you' stars & flowers
- [] Notify and thanks the contributors of the month

**Flowers**
- @sbernaldev
- @duartemendes
- @ntelkedzhiev
- @vitordagamagodoy 

**Stars**
- None so far

**Core Team**
- None so far

**Comment by js-kyle** [comment]
We also need to update the repo tagline to October 2018

**Comment by i0natan** [comment]
@js-kyle On this by tomorrow (the entire checklist).

We should also move sometime soon the repo to our org so anyone could make the change

/remind me in 1 day

**Comment by i0natan** [comment]
Closed in #266
