### ISSUE TITLE
February 2019 maintenance checklist

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#338]
**Maintainer on call**: @sagirk 

**Updates**
- [x] Update top badges with best practices item count, last update date and Node.js version
- [x] Ensure all translations are aligned with the English version
- [x] Update 'thank you' stars & flowers
- [x] Notify and thank the contributors of the month
- [x] Update news and updates

**Flowers**
@hozefaj
@el-ethan
@milkdeliver
@ArlindXh
@ttous
@LewisArdern

**Stars**

**Translation work**

**Comment by js-kyle** [comment]
@i0natan could we update the repo tagline please?

**Comment by i0natan** [comment]
@js-kyle Done!

**Comment by i0natan** [comment]
@sagirk All set

**Comment by sagirk** [comment]
[🎉🎉 Thank you contributors! 🎉🎉](https://github.com/i0natan/nodebestpractices/issues/354)
