### ISSUE TITLE
March 2019 maintenance checklist

### ISSUE THREAD

**Issue by sagirk** [i0natan/nodebestpractices#352]
**Maintainer on call**: @BrunoScheufler

**Updates**
- [ ] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [ ] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month
- [ ] Update news and updates
- [ ] Tweet it!

**Flowers**
- @DouglasMV
- @Francozeira
- @GabrielLidenor 
- @animir 
- @ryanouyang

**Stars**

**Translation work**
- @marcelosdm
- @DouglasMV
- @ryanouyang 
- @mperk

**Comment by sagirk** [comment]
News and Updates for March:
- BR translation now available (https://github.com/i0natan/nodebestpractices/pull/351). Heartfelt thanks to @marcelosdm! ❤️ 🎉

**Comment by i0natan** [comment]
@ryanouyang - Chinese translation

**Comment by i0natan** [comment]
@js-kyle What this handled (e.g. Tweets, flowers, etc)?

**Comment by BrunoScheufler** [comment]
@i0natan this issue was simply closed by the PR, flowers, etc. are handled 👍 Not sure what the tweet format should be though, any ideas?

**Comment by i0natan** [comment]
@BrunoScheufler PRs can be linked to issues and close them automatically?

Tweet - see @sagirk Thank You messgae from last month, it's looking good with many flowers and badges, you may create one linke this and prtscn into Twitter + some custom message:
"We had a great month! 2 new BP, 3 new translations, ..."
