### ISSUE TITLE
May operations checklist

### ISSUE THREAD

**Issue by js-kyle** [i0natan/nodebestpractices#398]
**Maintainer on call**: @js-kyle 

**Updates**
- [ ] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [ ] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month
- [ ] Update news and updates
- [ ] Tweet it!

**Flowers**

**Stars**

**Translation work**

**Comment by i0natan** [comment]
@js-kyle @BrunoScheufler April will get done in few hours
